### PR TITLE
#512 Added spinner indicating file is loading

### PR DESCRIPTION
**Pull request by Atmanea**
For small sized files this will barely make a change, but if the file is big enough then the user will see a loading spinner with the text "Loading file" in the middle. The spinner will be there until the engine is done counting all the lines in the file, at which point it will be replaced by the lines in the file instead.

### CODE REVIEW

**Comment by gustavjorlov** [comment]
Isn’t it possible to show the first fetched lines, and a spinner. And when line counting is done, just remove the spinner? 

We don’t want to hide content from users that we actually have

**Comment by Atmanea** [comment]
> Isn’t it possible to show the first fetched lines, and a spinner. And when line counting is done, just remove the spinner?
> 
> We don’t want to hide content from users that we actually have

As I understand it the reason we don't show the content is because we don't want any scrolling to take place while the engine is working.

**Comment by gustavjorlov** [comment]
Well, disable scrolling in that case ;)

**Comment by Atmanea** [comment]
> Well, disable scrolling in that case ;)

I tried to but I couldn't make it work properly and some solutions messed up the design. If you have any idea on how to do it I'd love to take some input :)

**Comment by MelindaSW** [comment]
https://www.npmjs.com/package/react-loading-overlay
You mean if it would look something like this? That would look nice. And the beginning of the file that is sent on opening would be visible underneath. I am not sure how to do something like that without that dependency though.

When disabling the scrolling, is the css value overflow-y: hidden the correct way to go? Or is there a better way? What did you try?

**Comment by Atmanea** [comment]
> https://www.npmjs.com/package/react-loading-overlay
> You mean if it would look something like this? That would look nice. And the beginning of the file that is sent on opening would be visible underneath. I am not sure how to do something like that without that dependency though.
> 
> When disabling the scrolling, is the css value overflow-y: hidden the correct way to go? Or is there a better way? What did you try?

That would look cool!

I tried to make it so that it doesn't hide, but that seems to be more complicated. Hiding it like you suggested and then setting it to auto makes the scrolling weird and slow for some reason, at least on my computer after trying to scroll a bit when the scrollbar shows itself.

**Comment by gustavjorlov** [comment]
Maybe alternate the value of the “data-is-scrollable” attribute on the list container

**Comment by gustavjorlov** [comment]
I’m just shooting from the hip here. But the important thing here is the user experience. 

Does it really affect anything badly if the user scrolls anyway? Try it out to get a feel for it, it might even be a non problem...

**Comment by Atmanea** [comment]
> I’m just shooting from the hip here. But the important thing here is the user experience.
> 
> Does it really affect anything badly if the user scrolls anyway? Try it out to get a feel for it, it might even be a non problem...

True...

**Comment by MelindaSW** [comment]
Yes, maybe if we just add a check to stop fetching of the new lines after scrolling past a few lines? I think that is where it breaks, since the value of the line count is needed in that request. But without the fetch triggering, it should be fine to scroll around.

**Comment by MelindaSW** [comment]
image
We discussed for a bit and decided to try this out (in the latest commit). It is reusing the indicator for showing a running file in the tab panel. Displaying it until the line count has arrived in the frontend. The user can scroll around in a limited amount of lines at the top of the file until the total line nr count is done and the rest of the file becomes available. Nothing seems to crash while doing so. It did so before and it makes me suspicious. Great if it works, but I will try it out some more and see if I manage to recreate the crash from before.
What do you think. Is it a good idea to reuse the indicator or should we add a separate indicator somewhere else? Is this good for now and for the upcoming release?

**Comment by gustavjorlov** [comment]
Why not. This kind of indicator should (in my opinion) stay out of the way until the user actually wonders “what’s going on?”

**Pull request merged**
