### PR TITLE
Implement fabric-ui color picker

### PR DESCRIPTION
**Pull request by Abdelkad3r**
Implemented Fabric UI ColorPicker instead of Github ColorPicker, now the user has all RGB colors to use.
Screenshot 2020-03-31 at 17 53 57
Screenshot 2020-03-31 at 17 54 26

### CODE REVIEW

**Comment by MelindaSW** [comment]
Nice. I really like to be able to choose from all the colors. It works on my machine.
The only thing that disturbs me is that it is quite big. The settings bar takes up a lot of the page when it is shown. This image is from the fabric ui docs page where you can disable more of the rows of color picker options below the big square. Another option could be to display it in a drop down menu triggered by clicking or hovering? So you can have the settings bar open without it blocking too much of the viewer. But it might just be something that only I react to, so wait and see what the other says:)
image

**Comment by Abdelkad3r** [comment]
Implemented Fabric-UI SwatchColorPicker instead of Fabric-UI ColorPicker component. SwatchColorPicker is better than ColorPicker because it's simple to use, also we choose 5 best colors to use as palette. And also SwatchColorPicker looks like better than ColorPicker component because of its size and design comparing to other UI design components in the product.
Screenshot 2020-04-06 at 16 57 18

**Comment by gustavjorlov** [comment]
Code in `TabPanelContainer` looks very similar to code already merged with pull request #499. Is this a mistake?

**Comment by MelindaSW** [comment]
The SwatchColorPicker works on my machine! 
I only have one question about the default red color. After picking another color it does not seem like we can choose it again? Maybe it is not a neccessary change, but could one of the colors in the picker be the default instead of the bright red?

**Comment by Abdelkad3r** [comment]
@gustavjorlov I just was working on two tasks in same time that's why i tried to modify #499 and have done it in #500 , so it's not a mistake, i'm just keeping the modification of #499 in #500

**Comment by Mathriok** [comment]
> @gustavjorlov I just was working on two tasks in same time that's why i tried to modify #499 and have done it in #500 , so it's not a mistake, i'm just keeping the modification of #499 in #500

If I understand this right you should be able to merge/rebase develop into this branch to get the changes from #499 in here.

**Comment by Abdelkad3r** [comment]
@MelindaSW I just updated the default matching text color/background color into the first color of Implemented Fabric UI SwatchColorPicker palette instead of the bright red.

**Pull request merged**
