### PR TITLE
#372 Implement Fabric UI in top panel

### PR DESCRIPTION
**Pull request by Doverstav**
This pull request implements Fabric UI components in the top panel of LogLady.

At the moment everything looks a bit white, which we could either try to improve now if we feel that it is needed, or we do it later when we implement theming.

I also chose to use underlined textfield, as the top panel felt a bit "fat" with the label on top of the textfield. See [Fabric UI documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield) for examples. I chose to add labels to the textfields as we in earlier discussion concluded that no labels is bad from a usability viewpoint. Of you wish to experiment with how the panel would look with non underlined textfield, simply remove the prop `underlined` in `TextFieldInput.js`.

In order to keep the panel slimmed down, the toggle uses and inline label. If we change the textfield to use labels on top, we may want to try this with the toggle as well. To try this, simply remove the `inline` prop in `SwitchButton.js`,

### CODE REVIEW

**Comment by Doverstav** [comment]
Yeah, I see what you mean. I disabled shrink on that stack item so now it wont shrink and force the label to act all wonky. Sadly the on/off text still get pushed off-screen, and I'm not sure what's a good solution for that. When the screen get smaller, something has to give. Either people with small screen can't use it (not the best solution, but easy), or we add some overflow (I think this is bad), or we try to make it somewhat responsive so that the stack gets several rows of components when space get scarce (probably the best solution, but takes some unknown amount of work).

**Comment by Eightquake** [comment]
That looks better :)
Maybe we should add a note to Projects about how to fix the other problem? It could be a large task on it's own.

**Comment by Doverstav** [comment]
I was thinking it could be a separate issue as well, but it wasn't a lot of work to do the bare minimum so I just did it. Each component now wraps as the screen gets smaller, so everything is usable. Please check it out, and tell me how it works!

One thing you could make a separate issue out of is improving the looks of it all. If you make the window small enough that both textfields wrap down, they are of different length which doesn't look very good. At the same time though, the window is very small so I'm not sure how useable LogLady is at that size, so maybe time spent doing that is better spent doing something else? I don't think it's a highly prioritizes issue at least, is my personal opinion.

**Comment by Eightquake** [comment]
I like it! A simple fix, but it would certainly be useful for someone that uses the application in a smaller window. I found no problems when resizing the window now 🙌

**Pull request merged**
