### PR TITLE
Feature/automate dev env#314

### PR DESCRIPTION
**Pull request by nejads**
Added a bash script and a homebrew file. Updated Readme file.

### CODE REVIEW

**Comment by Eightquake** [comment]
I already had Git, node/npm, and Brew installed. But neither git or node/npm were installed using Brew.

My steps:
1. `cd && curl --silent https://raw.githubusercontent.com/kits-ab/LogLady/feature/automate-dev-env%23314/bootstrap.sh | bash` which fails because macOS.Brewfile can't be found
2. `cd kits-ab/loglady && git checkout feature/automate-dev-env#314` to manually switch to this branch as the macOS.Brewfile isn't in develop branch yet
3. `cd && curl --silent https://raw.githubusercontent.com/kits-ab/LogLady/feature/automate-dev-env%23314/bootstrap.sh | bash` to continue installing using the Brewfile

I then run into some problems:
* `git pull` results in an error. `git config user.name and user.email` show my globally set information. This doesn't happen in my original folder for LogLady. Did you use root privileges to clone the repo? I am calling the git commands with my normal user. The error:

   ```
   git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   ```
* Having a filepath with spaces results in an error:
   ```
   ========> Cloning repository into /Users/victordavidsson/Downloads/bootstrap loglady test/kits-ab/loglady
   bash: line 52: test: too many arguments
   fatal: Too many arguments.
   ```

I'll try to install node and npm using Brew and see if the errors below still happen.

* `node` and `npm` were already installed and the script couldn't overwrite these, resulting in an error:

   ```
   ==> Installing yarn dependency: node
   ==> Downloading https://homebrew.bintray.com/bottles/node-12.10.0.mojave.bottle.tar.gz
   ==> Downloading from [a link]
   ==> Pouring node-12.10.0.mojave.bottle.tar.gz
   Error: The `brew link` step did not complete successfully
   The formula built, but is not symlinked into /usr/local
   Could not symlink bin/node
   Target /usr/local/bin/node already exists.
   Installing yarn has failed!
   Homebrew Bundle failed! 1 Brewfile dependency failed to install.
   ========> Brewfile installation failed
   ```
* After running this, `npm` is now messed up on my machine. Any npm command in any directory, that worked earlier, now throws an error that it cannot find a module. So it did change something. Running the bootstrap script _again_ results in a new error but doesn't fix the problem:
   ```
   ========> Installing packages within /Users/victordavidsson/kits-ab/loglady/macOS.Brewfile
   ========> Brewfile's dependencies are already satisfied.
   ========> Installing all npm packages in /Users/victordavidsson/kits-ab/loglady
   ========> Npm installation failed
   ```

**Comment by Eightquake** [comment]
But, aside from the problems I had, I really like what you did! It will let someone interested in the project get running much faster if they use macOS. 
Good idea and well done 👏

**Comment by nejads** [comment]
Thanks for your review comments. 

1. `git pull` error seems to be about your Github public key. 
2.  I've tested the script again and don't see any problem on line 52. It gets only a parameter. 
3. fixed `run test` script to checks tests automatically, thanks for pointing out that. 

I added a git checkout to this branch on line 59 in bootstrap file to solve temporary the problem with brew file. this line should remove after merging to the `develop` branch. 

I uninstalled all packages, git, node, brew and test the script after the latest changes and this is my terminal output: 
```
➜  ~ curl --silent https://raw.githubusercontent.com/kits-ab/LogLady/feature/automate-dev-env%23314/bootstrap.sh | bash
========> Prompting for sudo password
========> Sudo password updated
========> Installing Homebrew
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/sbin
/usr/local/opt
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /usr/local/sbin /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/sbin /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown soroush /usr/local/sbin /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/sbin /usr/local/opt /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /Users/soroush/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/soroush/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown soroush /Users/soroush/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 126202 (delta 10), reused 11 (delta 0), pack-reused 126175
Receiving objects: 100% (126202/126202), 30.02 MiB | 3.94 MiB/s, done.
Resolving deltas: 100% (92496/92496), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.0.2      -> 2.0.2
 * [new tag]         2.0.3      -> 2.0.3
 * [new tag]         2.0.4      -> 2.0.4
 * [new tag]         2.0.5      -> 2.0.5
 * [new tag]         2.0.6      -> 2.0.6
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
 * [new tag]         2.1.10     -> 2.1.10
 * [new tag]         2.1.11     -> 2.1.11
 * [new tag]         2.1.2      -> 2.1.2
 * [new tag]         2.1.3      -> 2.1.3
 * [new tag]         2.1.4      -> 2.1.4
 * [new tag]         2.1.5      -> 2.1.5
 * [new tag]         2.1.6      -> 2.1.6
 * [new tag]         2.1.7      -> 2.1.7
 * [new tag]         2.1.8      -> 2.1.8
 * [new tag]         2.1.9      -> 2.1.9
HEAD is now at 28fc26806 Merge pull request #6475 from dawidd6/create-go-mod
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 5040, done.
remote: Counting objects: 100% (5040/5040), done.
remote: Compressing objects: 100% (4840/4840), done.
remote: Total 5040 (delta 46), reused 581 (delta 9), pack-reused 0
Receiving objects: 100% (5040/5040), 4.02 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (46/46), done.
Checking out files: 100% (5056/5056), done.
Tapped 2 commands and 4828 formulae (5,081 files, 12.5MB).
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Next steps:
- Run `brew help` to get started
- Further documentation:
    https://docs.brew.sh
========> Homebrew installation succeeded
========> Cloning repository into /Users/soroush/kits-ab/loglady
Cloning into '/Users/soroush/kits-ab/loglady'...
remote: Enumerating objects: 249, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 4781 (delta 138), reused 152 (delta 75), pack-reused 4532
Receiving objects: 100% (4781/4781), 86.43 MiB | 4.36 MiB/s, done.
Resolving deltas: 100% (3242/3242), done.
Branch 'feature/automate-dev-env#314' set up to track remote branch 'feature/automate-dev-env#314' from 'origin'.
Switched to a new branch 'feature/automate-dev-env#314'
========> Loglady Repository cloned into /Users/soroush/kits-ab/loglady
========> Installing packages within /Users/soroush/kits-ab/loglady/macOS.Brewfile
Tapping heroku/brew
Using homebrew/bundle
Using homebrew/core
Tapping homebrew/services
Installing git
Installing git-open
Installing yarn
Homebrew Bundle complete! 7 Brewfile dependencies now installed.
========> Brewfile installation succeeded
========> Installing all npm packages in /Users/soroush/kits-ab/loglady
========> Npm installation succeeded
========> Checkes everything works in the project

> loglady@1.0.0 test /Users/soroush/kits-ab/loglady
> react-scripts test

PASS src/js/view/reducers/logInfoReducer.test.js
PASS src/js/view/components/helpers/logHelper.test.js
PASS src/js/helpers/recentFilesHelper.test.js
PASS src/js/view/reducers/menuReducer.test.js
PASS src/js/view/components/helpers/measureHelper.test.js
PASS src/js/view/components/helpers/regexHelper.test.js
PASS src/js/view/reducers/logViewerReducer.test.js
  ● Console

    console.log src/js/view/reducers/logViewerReducer.js:16
      ADDING
    console.log src/js/view/reducers/logViewerReducer.js:11
      SETTING
    console.log src/js/view/reducers/logViewerReducer.js:16
      ADDING

PASS src/js/adapters/fileReader.test.js
PASS src/js/view/components/helpers/statusBarHelper.test.js
PASS src/js/view/reducers/snackBarReducer.test.js
PASS src/js/view/reducers/settingsReducer.test.js
PASS src/js/view/configurations/configureStore.test.js
PASS src/js/view/AppContainer.test.js (5.388s)

Test Suites: 13 passed, 13 total
Tests:       89 passed, 89 total
Snapshots:   0 total
Time:        8.096s
Ran all test suites.
========> Npm tests succeeded
========> Run Loglady project

> loglady@1.0.0 dev /Users/soroush/kits-ab/loglady
> concurrently "BROWSER=none npm start" "wait-on http://localhost:3000 && electron --inspect ."

[0]
[0] > loglady@1.0.0 start /Users/soroush/kits-ab/loglady
[0] > react-scripts start
[0]
[0] Starting the development server...
[0]
[0] Compiled successfully!
[0]
[0] You can now view loglady in the browser.
[0]
[0]   Local:            http://localhost:3000/
[0]   On Your Network:  http://192.168.1.56:3000/
[0]
[0] Note that the development build is not optimized.
[0] To create a production build, use npm run build.
[0]
[1] Debugger listening on ws://127.0.0.1:9229/cc227461-c5b4-4727-b011-c10871609a98
[1] For help, see: https://nodejs.org/en/docs/inspector

```

**Comment by Eightquake** [comment]
About 1, yes, I noticed now that you change the remote to use SSH instead. I generated some SSH keys and it now works - but by using the origin remote Git receives while cloning this doesn't happen. Is it better to use SSH for GitHub? I have never done it before so I am curious.
```
The remote set in the script:
git remote -v
origin	git@github.com:kits-ab/loglady.git (fetch)
origin	git@github.com:kits-ab/loglady.git (push)
The remote if unchanged:
git remote -v
origin	https://github.com/kits-ab/loglady.git (fetch)
origin	https://github.com/kits-ab/loglady.git (push)
```

In 2, the problem only happens if the path has a space in it somewhere. I fixed this by adding quotes to every call that uses `$LOGLADY_LOCAL_REPO`. Example:
```bash
if test -e "$LOGLADY_LOCAL_REPO"; then
        substep "${LOGLADY_LOCAL_REPO} already exists"
        pull_latest "$LOGLADY_LOCAL_REPO"
        success "Pull successful in ${LOGLADY_LOCAL_REPO} repository"
```

**Comment by nejads** [comment]
Thanks @Eightquake 
I changed the script according to your feedback.

**Pull request merged**
