### PR TITLE
#306 Add auto-update

### PR DESCRIPTION
**Pull request by Eightquake**
This was surprisingly easy to do - electron-builder have the functionality built-in!

In this PR I have:
* Removed package electron-simple-updater in favour of [electron-update](https://github.com/electron-userland/electron-builder), as electron-updater has a lot more users
* Configured (which was like adding two rows) electron-updater. I made it so that if the user is not in developer mode, it will check for updates and download them to install in the background
* Configured electron-builder to publish releases to GitHub
* Switched the workflow on Travis from script to jobs/stages, making output more clean and informative while also only using electron-builder to deploy on the master branch - if on another branch electron-builder will only package
* Updated the README on how to create a release using this new system

### CODE REVIEW

**Comment by Eightquake** [comment]
I have noticed a problem in my .travis.yml, which is probably why Travis doesn't run a build for this PR.

About the questions:
* When the application is launched electron-updater sends a request to GitHub API about the latest release and looks for latest-[platform].yml. If the version in that file is newer than the application currently is, it will download it behind the scenes and replace it when you restart the application. The call to electron-updater is called `checkForUpdatesAndNotify` but I didn't get any notification on macOS, but I noticed that LogLady was updated to the new version in my Applications folder.
**However, we could test this branch separately before we merge it to make sure it works similarly on every platform!**
* In repository settings for Travis there was an environment variable called GH_TOKEN already, which electron-builder uses automatically. If you look at earlier Travis build logs you will notice electron-builder trying to publish a release (since that's the default operation) but skip it as there was no draft release.
* I wrote the README part before I tested it out on my own, and I noticed that because I override default publish to always, electron-builder will create a draft release if no release for the version is available. The update function doesn't care about draft releases.
**I will update the README to reflect this!**

**Comment by Doverstav** [comment]
I hope you find whatever the issue is with .travis.yml! 

Here are my reactions to your answers to my questions:
- Alright, that seems like a good enough solution for now. So if on launch LogLady finds a new release, the user won't have that release until the launch after that? Did I understand correctly?
 - Hmm, alright! I think that token could be old though, and it's probably not for @kitsmechanicalturk, because if I remember correctly it was there before we created that user. So we may have to look at updating that token.
 - I'm not sure I quite follow, but if I understand correctly, what's written down in the README right now is not final behavior?

**Comment by Eightquake** [comment]
* Yes, that is correct, the install won't be annoying for the user! electron-updater emits a few events that could be used to notify the user. I'll look into that more!
* Ah, you are right! It probably is outdated. I'll update it to a newer one.
* Following the steps in the README won't cause any issues, but not following it and merging without a release draft wouldn't cause any issues either. I will update the README to mention both of the options available.

**Comment by Doverstav** [comment]
- Alright, sounds great!
- Can you just re-use the token from the .travis.yml? Because that's a github access token encrypted with travis CLI, and without really knowing that should work as an envrinment variable as well, right? Otherwise, if setting the travis token online is like setting it in the .travis.yml, I had some issues encrypting, and had to run `travis encrypt --pro`, see [here for some more info](https://travis-ci.community/t/401-bad-credentials-octokit-unauthorized/5355)
- Ok, then I'm onboard!

**Comment by Eightquake** [comment]
I don't think there's a way to decrypt from Travis - and environment variables set in repository settings gets encrypted so it would be doubly encrypted. I think I'll just create a new one, with a name that shows it's for electron-updater and not Travis.

**Comment by Doverstav** [comment]
Ah, ok, yeah, sounds like it's best to just create a new token then. I just thought I'd ask so you didn't have to do some token fiddling in vain!

**Comment by Eightquake** [comment]
Update: This time I got a notification! Don't know why I didn't get one the other time, but no matter.
Here's how it looks, and it explains the process of updating for the user:

Screenshot 2019-12-19 at 17 44 45

**Comment by Doverstav** [comment]
Cool, that looks really nice!

**Pull request merged**
